package com.hellokurukshetra.admin

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import com.hellokurukshetra.admin.data.ApiClient
import kotlinx.coroutines.launch
import org.json.JSONArray
import org.json.JSONObject

private val Navy=Color(0xFF07111F);private val Yellow=Color(0xFFFFC107)
private enum class Section(val title:String,val icon:androidx.compose.ui.graphics.vector.ImageVector){DASHBOARD("Dashboard",Icons.Default.Dashboard),PEOPLE("People",Icons.Default.People),VERIFICATION("Verification",Icons.Default.VerifiedUser),RIDES("Rides",Icons.Default.DirectionsCar),PAYMENTS("Payments",Icons.Default.Payments),EMERGENCY("Emergency",Icons.Default.Warning),SUPPORT("Support",Icons.Default.SupportAgent),PROMOTIONS("Promotions",Icons.Default.LocalOffer),NOTIFICATIONS("Notifications",Icons.Default.Notifications),SETTINGS("Branding & Pricing",Icons.Default.Settings)}

@Composable fun AdminApp(api:ApiClient){var logged by remember{mutableStateOf(api.isLoggedIn())};if(logged)Shell(api){api.logout();logged=false}else Login(api){logged=true}}

@Composable private fun Login(api:ApiClient,onLogin:()->Unit){val scope=rememberCoroutineScope();var id by remember{mutableStateOf("")};var pass by remember{mutableStateOf("")};var busy by remember{mutableStateOf(false)};var error by remember{mutableStateOf<String?>(null)};Box(Modifier.fillMaxSize().background(Navy),contentAlignment=Alignment.Center){Card(Modifier.padding(24.dp).fillMaxWidth().widthIn(max=460.dp)){Column(Modifier.padding(28.dp),verticalArrangement=Arrangement.spacedBy(14.dp)){Text("HELLO KURUKSHETRA",color=Navy,fontWeight=FontWeight.Bold);Text("Admin Control Center",style=MaterialTheme.typography.headlineMedium,fontWeight=FontWeight.Bold);Text("Secure administrator sign-in",color=Color.Gray);OutlinedTextField(id,{id=it},label={Text("Username or email")},singleLine=true,modifier=Modifier.fillMaxWidth());OutlinedTextField(pass,{pass=it},label={Text("Password")},singleLine=true,visualTransformation=androidx.compose.ui.text.input.PasswordVisualTransformation(),modifier=Modifier.fillMaxWidth());error?.let{Text(it,color=MaterialTheme.colorScheme.error)};Button(onClick={if(id.isBlank()||pass.isBlank()){error="Enter username and password";return@Button};busy=true;scope.launch{api.login(id,pass).onSuccess{root->val d=root.optJSONObject("data")?:JSONObject();api.saveSession(d);api.get("/admin/analytics").onSuccess{onLogin()}.onFailure{api.logout();error="Account does not have active admin access."}}.onFailure{error=it.message};busy=false}},enabled=!busy,colors=ButtonDefaults.buttonColors(containerColor=Yellow,contentColor=Navy),modifier=Modifier.fillMaxWidth().height(52.dp)){if(busy)CircularProgressIndicator(strokeWidth=2.dp,modifier=Modifier.size(22.dp))else Text("SIGN IN",fontWeight=FontWeight.Bold)}}}}}

@OptIn(ExperimentalMaterial3Api::class)
@Composable private fun Shell(api:ApiClient,logout:()->Unit){var section by remember{mutableStateOf(Section.DASHBOARD)};var open by remember{mutableStateOf(false)};ModalNavigationDrawer(drawerState=rememberDrawerState(if(open)DrawerValue.Open else DrawerValue.Closed),drawerContent={ModalDrawerSheet{Column(Modifier.background(Navy).fillMaxHeight().width(300.dp).padding(16.dp)){Text("Hello Kurukshetra",color=Yellow,style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Bold);Text("ADMIN PANEL",color=Color.White);Spacer(Modifier.height(20.dp));Section.values().forEach{item->NavigationDrawerItem(label={Text(item.title)},selected=section==item,onClick={section=item;open=false},icon={Icon(item.icon,null)},colors=NavigationDrawerItemDefaults.colors(selectedContainerColor=Yellow,selectedTextColor=Navy,selectedIconColor=Navy,unselectedTextColor=Color.White,unselectedIconColor=Color.White))};Spacer(Modifier.weight(1f));NavigationDrawerItem(label={Text("Logout")},selected=false,onClick=logout,icon={Icon(Icons.Default.Logout,null)})}}}){Scaffold(topBar={TopAppBar(title={Text(section.title,fontWeight=FontWeight.Bold)},navigationIcon={IconButton({open=true}){Icon(Icons.Default.Menu,"Menu")}},actions={IconButton(logout){Icon(Icons.Default.Logout,"Logout")}},colors=TopAppBarDefaults.topAppBarColors(containerColor=Navy,titleContentColor=Color.White,navigationIconContentColor=Color.White,actionIconContentColor=Color.White))}){p->Box(Modifier.padding(p).fillMaxSize()){when(section){Section.DASHBOARD->Dashboard(api);Section.PEOPLE->ListScreen(api,"People","/admin/people?limit=50","items");Section.VERIFICATION->ActionList(api,"Verification","/admin/verification/requests?limit=50","items",listOf("Approve"){id->api.patch("/admin/verification/requests/"+id,JSONObject().put("status","VERIFIED"))});Section.RIDES->ActionList(api,"Operational Rides","/admin/rides?limit=50","items",listOf("Cancel"){id->api.post("/admin/rides/"+id+"/cancel",JSONObject().put("reason","Admin cancellation"))});Section.PAYMENTS->ActionList(api,"Payments","/admin/finance/payments?limit=50","items",listOf("Refund"){id->api.post("/admin/finance/payments/"+id+"/refund",JSONObject().put("reason","Admin refund"))});Section.EMERGENCY->ActionList(api,"Emergency Incidents","/admin/emergency/incidents?limit=100","items",listOf("Acknowledge"){id->api.post("/admin/emergency/incidents/"+id+"/acknowledge")},listOf("Escalate"){id->api.post("/admin/emergency/incidents/"+id+"/escalate")},listOf("Resolve"){id->api.post("/admin/emergency/incidents/"+id+"/resolve")});Section.SUPPORT->ListScreen(api,"Support Tickets","/admin/support/tickets?limit=50","items");Section.PROMOTIONS->ListScreen(api,"Promotions","/admin/promotions?limit=50","items");Section.NOTIFICATIONS->ListScreen(api,"Notifications","/admin/notifications?limit=50","notifications");Section.SETTINGS->Settings(api)}}}}}}

@Composable private fun Dashboard(api:ApiClient){var data by remember{mutableStateOf<JSONObject?>(null)};var err by remember{mutableStateOf<String?>(null)};LaunchedEffect(Unit){api.get("/admin/analytics").onSuccess{data=it}.onFailure{err=it.message}};val k=data?.optJSONObject("kpis");LazyColumn(Modifier.fillMaxSize().padding(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){item{Text("Operations overview",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold)};err?.let{item{Error(it)}};item{Row(horizontalArrangement=Arrangement.spacedBy(10.dp)){Kpi("Users",k?.optInt("users",0)?:0,Modifier.weight(1f));Kpi("Active",k?.optInt("activeUsers",0)?:0,Modifier.weight(1f))}};item{Row(horizontalArrangement=Arrangement.spacedBy(10.dp)){Kpi("Drivers",k?.optInt("approvedDrivers",0)?:0,Modifier.weight(1f));Kpi("Guides",k?.optInt("approvedGuides",0)?:0,Modifier.weight(1f))}};item{Row(horizontalArrangement=Arrangement.spacedBy(10.dp)){Kpi("Rides",k?.optInt("rides",0)?:0,Modifier.weight(1f));Kpi("Payments",k?.optInt("payments",0)?:0,Modifier.weight(1f))}};item{Row(horizontalArrangement=Arrangement.spacedBy(10.dp)){Kpi("Verification",k?.optInt("verificationRequests",0)?:0,Modifier.weight(1f));Kpi("Support",k?.optInt("supportTickets",0)?:0,Modifier.weight(1f))}};item{Breakdown("Ride status",data?.optJSONObject("breakdowns")?.optJSONObject("rides"))};item{Breakdown("Payment status",data?.optJSONObject("breakdowns")?.optJSONObject("payments"))};item{Breakdown("Verification status",data?.optJSONObject("breakdowns")?.optJSONObject("verificationRequests"))}}}

@Composable private fun ListScreen(api:ApiClient,title:String,endpoint:String,key:String){var rows by remember{mutableStateOf<List<JSONObject>>(emptyList())};var err by remember{mutableStateOf<String?>(null)};LaunchedEffect(endpoint){api.get(endpoint).onSuccess{rows=extract(it,key)}.onFailure{err=it.message}};LazyColumn(Modifier.fillMaxSize().padding(16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){err?.let{item{Error(it)}};items(rows){JsonCard(title,it)};if(rows.isEmpty()&&err==null)item{Empty()}}}

@Composable private fun ActionList(api:ApiClient,title:String,endpoint:String,key:String,vararg actionPairs:List<Pair<String,suspend(String)->Result<JSONObject>>>){var rows by remember{mutableStateOf<List<JSONObject>>(emptyList())};var err by remember{mutableStateOf<String?>(null)};val scope=rememberCoroutineScope();fun load(){scope.launch{api.get(endpoint).onSuccess{rows=extract(it,key)}.onFailure{err=it.message}}};LaunchedEffect(endpoint){load()};LazyColumn(Modifier.fillMaxSize().padding(16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){err?.let{item{Error(it)}};items(rows){row->val id=row.optString("id");Card(Modifier.fillMaxWidth()){Column(Modifier.padding(14.dp)){Text(pretty(row),fontWeight=FontWeight.Bold);Text(compact(row),maxLines=5,color=Color.DarkGray);if(id.isNotBlank())Row{actionPairs.flatMap{it}.forEach{a->OutlinedButton(onClick={scope.launch{a.second(id).onFailure{err=it.message}.onSuccess{load()}}},modifier=Modifier.padding(end=6.dp)){Text(a.first)}}}}}}}}

@Composable private fun Settings(api:ApiClient){var branding by remember{mutableStateOf<JSONObject?>(null)};var pricing by remember{mutableStateOf<JSONObject?>(null)};LaunchedEffect(Unit){api.get("/admin/branding").onSuccess{branding=it};api.get("/admin/pricing/ride").onSuccess{pricing=it}};LazyColumn(Modifier.fillMaxSize().padding(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){item{Text("Backend configuration",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold)};item{JsonCard("Branding",branding?:JSONObject())};item{JsonCard("Ride pricing",pricing?:JSONObject())}}}

@Composable private fun Kpi(label:String,value:Int,m:Modifier){Card(m){Column(Modifier.padding(16.dp)){Text(label,color=Color.Gray);Text(value.toString(),style=MaterialTheme.typography.headlineMedium,fontWeight=FontWeight.Bold,color=Navy)}}}
@Composable private fun Breakdown(title:String,json:JSONObject?){if(json==null)return;Card(Modifier.fillMaxWidth()){Column(Modifier.padding(14.dp)){Text(title,fontWeight=FontWeight.Bold);for(k in json.keys())Text(k+": "+json.opt(k),Modifier.padding(top=5.dp))}}}
@Composable private fun JsonCard(title:String,j:JSONObject){Card(Modifier.fillMaxWidth()){Column(Modifier.padding(14.dp)){Text(title,fontWeight=FontWeight.Bold);Text(compact(j),color=Color.DarkGray)}}}
@Composable private fun Error(s:String){Card(colors=CardDefaults.cardColors(containerColor=Color(0xFFFFEAEA))){Text(s,Modifier.padding(14.dp),color=Color(0xFF9A0000))}}
@Composable private fun Empty(){Card(Modifier.fillMaxWidth()){Text("No records found",Modifier.padding(24.dp),color=Color.Gray)}}
private fun extract(root:JSONObject,key:String):List<JSONObject>{val out=mutableListOf<JSONObject>();val data=root.optJSONObject("data");val a=root.optJSONArray(key)?:data?.optJSONArray(key);if(a!=null)for(i in 0 until a.length())a.optJSONObject(i)?.let{out.add(it)};return out}
private fun pretty(j:JSONObject)=j.optString("name").ifBlank{j.optString("title").ifBlank{j.optString("code").ifBlank{j.optString("id","Record")}}}
private fun compact(j:JSONObject):String{val p=mutableListOf<String>();for(k in j.keys()){val v=j.opt(k);if(v !is JSONObject&&v !is JSONArray)p.add(k+"="+v)};return p.take(8).joinToString(" • ")}
