package com.hellokurukshetra.admin.feature.verification
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import com.hellokurukshetra.admin.data.ApiClient
import com.hellokurukshetra.admin.ui.*
import org.json.JSONObject
@Composable fun VerificationScreen(api:ApiClient){var rows by remember{mutableStateOf<List<JSONObject>>(emptyList())};var error by remember{mutableStateOf<String?>(null)};var selected by remember{mutableStateOf<JSONObject?>(null)};var busy by remember{mutableStateOf(false)};fun load(){};LaunchedEffect(Unit){val all=mutableListOf<JSONObject>();for(role in listOf("DRIVER","GUIDE"))for(status in listOf("UNDER_VERIFICATION","RESUBMITTED","PENDING")){api.get("/admin/verification/requests?role="+role+"&status="+status+"&limit=100").onSuccess{all+=extractVerification(it)}};rows=all.distinctBy{it.optString("id")};if(rows.isEmpty())error=null};LazyColumn(Modifier.fillMaxSize().padding(20.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){item{PageHeader("Provider verification","Review driver and guide applications before activation.")};error?.let{item{ErrorBanner(it)}};if(rows.isEmpty()&&error==null)item{EmptyState("No pending provider verification requests.")};items(rows,key={it.optString("id")}){r->val u=r.optJSONObject("user");Card(Modifier.fillMaxWidth()){Column(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text(u?.optString("name").orEmpty().ifBlank{"Provider"},style=MaterialTheme.typography.titleMedium);StatusBadge(r.optString("status","PENDING"))};Text("Documents: "+(r.optJSONArray("documents")?.length()?:0)+" • Live: "+(r.optJSONObject("liveSession")?.optString("status").orEmpty().ifBlank{"NOT_STARTED"}));Row{OutlinedButton({selected=r}){Text("Review")};Spacer(Modifier.width(8.dp));Button(enabled=!busy,onClick={busy=true;api.patch("/admin/verification/requests/"+r.optString("id"),JSONObject().put("status","VERIFIED")).onSuccess{rows=rows.filterNot{it.optString("id")==r.optString("id")}}.onFailure{error=it.message};busy=false}){Text("Approve")}}}}}}};selected?.let{r->AlertDialog(onDismissRequest={selected=null},title={Text("Verification details")},text={Text(summary(r)+"\n\nCheck documents and live verification before approval.")},confirmButton={TextButton({selected=null}){Text("Close")}})}}}
private fun extractVerification(root:JSONObject):List<JSONObject>{for(k in listOf("items","requests","verificationRequests")){val v=extract(root,k);if(v.isNotEmpty())return v};return emptyList()}
